services:
  nginx:
    image: nginx:1.25-alpine
    container_name: ama_nginx
    depends_on:
      - app
    volumes:
      - ./public:/var/www/public:ro
      - ./docker/prod/nginx/default.conf:/etc/nginx/nginx.conf:ro  # <-- změna zde
      - storage_data:/var/www/storage
      - database_data:/var/www/database
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ama.rule=Host(`amatelier.cz`) || Host(`www.amatelier.cz`)"
      - "traefik.http.routers.ama.entrypoints=websecure"
      - "traefik.http.routers.ama.tls.certresolver=cloudflare"
      - "traefik.http.services.ama.loadbalancer.server.port=80"
    networks:
      - traefik
      - ama
    restart: unless-stopped

  app:
    container_name: ama_app
    build:
      context: .
      dockerfile: docker/prod/Dockerfile
    image: ama-prod:latest
    working_dir: /var/www
    env_file:
      - ./.env.production
    volumes:
      - ./public:/var/www/public:cached
      - database_data:/var/www/database       # named volume pro zápis
      - storage_data:/var/www/storage
      - ./.env.production:/var/www/.env:ro
    expose:
      - "9000"
    networks:
      - ama
    restart: unless-stopped
    command: >
      sh -c "php artisan optimize:clear &&
             php-fpm"

  node:
    image: node:20-alpine
    container_name: ama_node
    working_dir: /var/www
    volumes:
      - ./public:/var/www/public
      - ./resources:/var/www/resources
      - ./package.json:/var/www/package.json
      - ./package-lock.json:/var/www/package-lock.json
    networks:
      - ama
    entrypoint: ["sh", "-c"]
    command: "npm install && npm run build"
    restart: "no"

volumes:
  storage_data:
  database_data:

networks:
  traefik:
    external: true
  ama:
    external: true
