server {
    listen 80;
    server_name ama.cz www.amatelier.cz;

    root /var/www/public;
    index index.php index.html;

    # Gzip a caching pro statické soubory
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # PHP-FPM
    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass ama_app:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_buffers 16 16k;
        fastcgi_buffer_size 32k;
    }

    location ~* ^(.+)\.(png|jpg|jpeg)$ {
        add_header Vary Accept;
        try_files $uri =404;
    }

    location ~ /\.ht {
        deny all;
    }

    client_max_body_size 50M;
    sendfile on;
    keepalive_timeout 65;
}
